### ISSUE TITLE
Specify inspec output formats in .kitchen.yml

### ISSUE THREAD

**Issue by cheesesashimi** [chef/kitchen-inspec#26]
If one were to run `inspec exec`, you can pass in something like `inspec exec --format=documentation` so that the output is more descriptive and meaningful. Presently, there appears to be no way to do that from within test-kitchen.

By way of example. The default output leaves something to be desired:

```
$ kitchen verify linux-rhel-71
-----> Starting Kitchen (v1.4.2)
-----> Verifying <linux-rhel-71>...
.......

Finished in 0.93712 seconds (files took 0.67007 seconds to load)
7 examples, 0 failures

       Finished verifying <linux-rhel-71> (0m1.30s).
-----> Kitchen is finished. (0m23.15s)
```

It would be nice if one could obtain output like this:

```
System Package ntp
  should be installed

System Package ntpdate
  should be installed
```

After some discussion on Slack, it appears that the right place to do that might be in [https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L108](https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L108), which I'm including for posterity. I don't mind trying to implement this myself and sending a PR, but I'm including the above link in the event I'm unable to do so.

**Comment by chris-rock** [comment]
Thanks @cheesesashimi for adding this. I close that issue. Please re-open if this `kitchen-inspec` is not doing what you need.

**Comment by conorsch** [comment]
Thanks @cheesesashimi! Is there a way to make the error output more concise? Specifically, I'd like to silence the traceback from a failure and display only the failure message.

For example, I'd like to see only this:

```
  2) gem package riemann-tools should be installed
     Failure/Error: versions = params[2].split(',')
```

Instead of this montrosity:

```

  2) gem package riemann-tools should be installed
     Failure/Error: versions = params[2].split(',')

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /home/conor/.gem/ruby/2.1.0/gems/inspec-0.9.8/lib/resources/gem.rb:31:in `info'
     # /home/conor/.gem/ruby/2.1.0/gems/inspec-0.9.8/lib/resources/gem.rb:38:in `installed?'
     # /home/conor/.gem/ruby/2.1.0/gems/inspec-0.9.8/lib/matchers/matchers.rb:97:in `block (2 levels) in <top (required)>'
     # ./test/integration/default/riemann_dash_spec.rb:10:in `block (2 levels) in load'
     # /home/conor/.gem/ruby/2.1.0/gems/inspec-0.9.8/lib/inspec/runner.rb:117:in `run_with'
     # /home/conor/.gem/ruby/2.1.0/gems/inspec-0.9.8/lib/inspec/runner.rb:113:in `run'
     # /home/conor/.gem/ruby/2.1.0/gems/kitchen-inspec-0.10.1/lib/kitchen/verifier/inspec.rb:43:in `call'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:398:in `block in verify_action'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:394:in `verify_action'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
     # /home/conor/.gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action
```

The verbose format obscures the error report with unnecessary info about inspec's internals.
