### ISSUE TITLE
Can't verify when used with kitchen-digitalocean provider

### ISSUE THREAD

**Issue by artem-sidorenko** [chef/kitchen-inspec#78]
Create and converge work without any problems, but verify fails with following error message:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [You must configure at least one authentication method for SSH: Password or key.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

.kitchen.yml:
```yml
---
driver:
  name: digitalocean
  size: 512mb

platforms:
- name: centos-7-0-x64
- name: ubuntu-14-04-x64

provisioner:
  name: chef_zero

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[bla::default]
```

kitchen log:
```
I, [2016-04-14T22:51:36.877664 #19221]  INFO -- Kitchen: -----> Starting Kitchen (v1.6.0)
I, [2016-04-14T22:51:37.772431 #19221]  INFO -- Kitchen: -----> Converging <default-centos-7-0-x64>...
I, [2016-04-14T22:51:37.772636 #19221]  INFO -- Kitchen: -----> Converging <default-ubuntu-14-04-x64>...
I, [2016-04-14T22:52:13.444049 #19221]  INFO -- Kitchen: -----> Setting up <default-ubuntu-14-04-x64>...
I, [2016-04-14T22:52:13.447798 #19221]  INFO -- Kitchen: -----> Verifying <default-ubuntu-14-04-x64>...
I, [2016-04-14T22:52:33.439790 #19221]  INFO -- Kitchen: -----> Setting up <default-centos-7-0-x64>...
I, [2016-04-14T22:52:33.442952 #19221]  INFO -- Kitchen: -----> Verifying <default-centos-7-0-x64>...
E, [2016-04-14T22:52:33.449197 #19221] ERROR -- Kitchen: ------Exception-------
E, [2016-04-14T22:52:33.449383 #19221] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-04-14T22:52:33.449470 #19221] ERROR -- Kitchen: Message: Failed to complete #verify action: [You must configure at least one authentication method for SSH: Password or key.]
E, [2016-04-14T22:52:33.449545 #19221] ERROR -- Kitchen: ---Nested Exception---
E, [2016-04-14T22:52:33.449616 #19221] ERROR -- Kitchen: Class: Train::ClientError
E, [2016-04-14T22:52:33.449685 #19221] ERROR -- Kitchen: Message: You must configure at least one authentication method for SSH: Password or key.
E, [2016-04-14T22:52:33.449756 #19221] ERROR -- Kitchen: ------Backtrace-------
E, [2016-04-14T22:52:33.449824 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/r-train-0.10.3/lib/train/transports/ssh.rb:84:in `validate_options'
E, [2016-04-14T22:52:33.449897 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/r-train-0.10.3/lib/train/transports/ssh.rb:67:in `connection'
E, [2016-04-14T22:52:33.449968 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.14.8/lib/inspec/backend.rb:23:in `create'
E, [2016-04-14T22:52:33.450038 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.14.8/lib/inspec/runner.rb:46:in `configure_transport'
E, [2016-04-14T22:52:33.450109 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.14.8/lib/inspec/runner.rb:30:in `initialize'
E, [2016-04-14T22:52:33.450180 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-inspec-0.12.3/lib/kitchen/verifier/inspec.rb:69:in `new'
E, [2016-04-14T22:52:33.450281 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-inspec-0.12.3/lib/kitchen/verifier/inspec.rb:69:in `call'
E, [2016-04-14T22:52:33.450401 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:421:in `block in verify_action'
E, [2016-04-14T22:52:33.450474 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `call'
E, [2016-04-14T22:52:33.450544 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
E, [2016-04-14T22:52:33.450621 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
E, [2016-04-14T22:52:33.450697 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-04-14T22:52:33.450773 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
E, [2016-04-14T22:52:33.450863 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:415:in `verify_action'
E, [2016-04-14T22:52:33.450935 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-04-14T22:52:33.451008 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
E, [2016-04-14T22:52:33.451080 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-04-14T22:52:33.451182 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:160:in `verify'
E, [2016-04-14T22:52:33.451281 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
E, [2016-04-14T22:52:33.451394 #19221] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2016-04-14T22:52:33.451521 #19221] ERROR -- Kitchen: ----------------------
```

**Comment by artem-sidorenko** [comment]
Transport configuration in .kitchen.yml solves this
```yml
....
platforms:
- name: centos-7-0-x64
  transport:
   ssh_key: /tmp/ssh-key-digocean/id_rsa
- name: ubuntu-14-04-x64
  transport:
   ssh_key: /tmp/ssh-key-digocean/id_rsa
....
```

but somehow its a bit strange: converge works with keys provided by ssh-agent or keys in default ssh path, but verify breakts

**Comment by chris-rock** [comment]
@artem-sidorenko we had a similar problem with `kitchen-docker`. Both plugins use a kitchen legacy approach. We added additional capabilities in test-kitchen to cover that: https://github.com/test-kitchen/test-kitchen/pull/944 Do you use test-kitchen 1.7?

**Comment by artem-sidorenko** [comment]
@chris-rock no, I use test-kitchen 1.6.0 from current chef-dk. 
But after your hint I tested it with test-kitchen 1.7.3 and see the same problem:
```
$ chef exec ~/.chefdk/gem/ruby/2.1.0/bin/kitchen verify
-----> Starting Kitchen (v1.7.3)
-----> Setting up <default-centos-7-0-x64>...
$$$$$$ Running legacy setup for 'Digitalocean' Driver
       Finished setting up <default-centos-7-0-x64> (0m0.00s).
-----> Verifying <default-centos-7-0-x64>...
       Detected alternative framework tests for `inspec`
       Search `.../test/integration/default/inspec` for tests
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [You must configure at least one authentication method for SSH: Password or key.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by pwlae** [comment]
Have same problem with Rackspace provider. Kitchen 1.11.1

**Comment by smartb-pair** [comment]
We also see this with `kitchen-joyent`

**Comment by rhoegg** [comment]
I ran into this with [kitchen-terraform|https://github.com/newcontext/kitchen-terraform] as well

**Comment by iancward** [comment]
I see the same with test-kitchen 1.13.2 and kitchen-openstack:
```
➜  my_cookbook git:(master) ✗ kitchen verify master
-----> Starting Kitchen (v1.13.2)
WARN: Unresolved specs during Gem::Specification.reset:
      unf_ext (>= 0)
      CFPropertyList (~> 2.2)
      ffi (~> 1.9)
      rainbow (~> 2)
      diff-lcs (< 2.0, >= 1.2.0)
      winrm (~> 2.0)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Verifying <master-chef12-rhel6>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Client error, can't connect to 'ssh' backend: You must configure at least one authentication method for SSH: Agent, Key or Password.] on master-chef12-rhel6
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

➜  my_cookbook git:(master) ✗ chef -v
Chef Development Kit Version: 1.0.3
chef-client version: 12.16.42
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.13.2
➜  my_cookbook git:(master) ✗ chef gem list --local |grep kitchen
kitchen-docker (2.6.0)
kitchen-dokken (1.0.4)
kitchen-ec2 (1.2.0)
kitchen-inspec (0.17.0, 0.16.1)
kitchen-openstack (3.5.0, 3.4.0, 3.2.0, 3.1.0)
kitchen-sync (2.1.2, 2.1.1)
kitchen-transport-rsync (0.1.2)
kitchen-vagrant (1.1.0, 0.20.0)
test-kitchen (1.16.0, 1.15.0, 1.14.2, 1.13.2, 1.13.0, 1.11.1, 1.11.0)
```

**Comment by iancward** [comment]
Come to find out, I had a `transport` section defined in a file that's pointed to from KITCHEN_LOCAL_YAML, and it had `username` defined, but it was missing `ssh_key`. I added `ssh_key` to the transport section and it seems to be working now.
